services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
